[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Projects"
weight = 20

[[main]]
name = "Scripts"
parent = "Projects"
pageRef = "scripts"
weight = 25

[[main]]
name = "Distro"
parent = "Projects"
pageRef = "iso"
weight = 30

[[main]]
name = "My Gear"
pageRef = "Gear"
weight = 35

[[main]]
name = "News"
pageRef = "news"
weight = 40

[[main]]
name = "Merch"
url = "https://shop.xerolinux.xyz/"
weight = 45

[[main]]
name = "Wiki"
url = "https://wiki.xerolinux.xyz/"
weight = 50

[[main]]
pre = "rss"
url = "/index.xml"
weight = 55

[[footer]]
none = "none"
