[[main]]
name = "About"
pre = "eye"
pageRef = "about"
identifier = "Aoxiwtse7L"
weight = 1

[[main]]
name = "Projects"
pre = "lock"
pageRef = "projects"
identifier = "yjhEZtlj41"
weight = 2

[[main]]
name = "Support"
pre = "ko-fi"
pageRef = "support"
identifier = "lCg1v3VPgs"
weight = 3

[[main]]
name = "Blog"
pre = "fire"
url = "https://blog.xerolinux.xyz"
identifier = "W3EFHAU6qb"
weight = 4

[[main]]
name = "Forums"
pre = "link"
url = "https://forum.xerolinux.xyz"
identifier = "UYjuTjvH9W"
weight = 5

[[main]]
name = "Github"
pre = "github"
url = "https://github.com/xerolinux"
identifier = "R5K4LrER4e"
weight = 6

[[main]]
name = "RSS"
pre = "rss"
url = "https://xerolinux.xyz/index.xml"
identifier = "dQrZgi97Wk"
weight = 7

[[footer]]
none = "none"
