[[main]]
name = "About"
pre = "eye"
pageRef = "about"
identifier = "Aoxiwtse7L"
weight = 1

[[main]]
name = "Projects"
pre = "lock"
pageRef = "projects"
identifier = "yjhEZtlj41"
weight = 2

[[main]]
name = "The Gear"
pre = "fire"
pageRef = "Gear"
identifier = "ZFozXYGy5E"
weight = 3

[[main]]
name = "Support"
pre = "ko-fi"
pageRef = "support"
identifier = "lCg1v3VPgs"
weight = 4

[[main]]
name = "News"
pre = "globe"
pageRef = "news"
identifier = "WmM3BrLWvc"
weight = 5

[[main]]
name = "RSS"
pre = "rss"
url = "https://xerolinux.xyz/index.xml"
identifier = "dQrZgi97Wk"
weight = 6

[[footer]]
none = "none"
