[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Projects"
weight = 20

[[main]]
name = "Scripts"
parent = "Projects"
pageRef = "scripts"
weight = 25

[[main]]
name = "The ISO"
parent = "Projects"
pageRef = "iso"
weight = 30

[[main]]
name = "My Gear"
pageRef = "Gear"
weight = 35

[[main]]
name = "Support"
pageRef = "support"
weight = 40

[[main]]
name = "News"
pageRef = "news"
weight = 45

[[footer]]
none = "none"
